order/urls.py
from  django.conf.urls import url, patterns
from order.views import *

urlpatterns = patterns(
	'',
	url(r'^$', view=index_page, name='index'),
	url(r'^menu', view=FoodMenuView.as_view(), name='menu'),
	url(r'^add-item/$', view=add_item_to_cart, name='add'),
	url(r'^remove-item/$', view=remove_food_from_cart, name='remove'),
	url(r'^cart/$', view=get_food_from_cart, name='cart'),
	url(r'^logout/$', view=user_logout, name='logout'),
	url(r'^payment-successful/$', view=success_full_payment, name='payment-successful'),
)

resturant/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from  resturant import settings
admin.site.site_header = "Burger Chef Resturant"
handler404 = 'order.views.handler404'
handler500 = 'mysite.views.handler500'
urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^fast/', include('order.urls')),
]


if settings.DEBUG:
	urlpatterns += patterns(
		'django.views.static',
		(r'^media/(?P<path>.*)',
		 'serve',
		 {'document_root': settings.MEDIA_ROOT})
	)

order/models.py
from time import timezone
from django.contrib.auth.models import User
from django.db import models

from string import join
# Create your models here.
from django.utils.html import strip_tags, format_html
from django.utils.safestring import SafeUnicode

"""
our food class that represent the food table
in our db
"""


class Food(models.Model):
	food_name = models.CharField(max_length=255)
	food_price = models.IntegerField(default=50)
	food_time_duration = models.TimeField()
	food_image = models.ImageField(upload_to='uploads', blank=True)
	food_availability = models.BooleanField(default=True)

	class Meta:
		verbose_name = "Meal"
		verbose_name_plural = "Meal's"

	def __unicode__(self):
		return self.food_name


"""
our customer class that represent the
customer table in our db it has the user has
a foreign key so each customer is a user when created
"""


class Customer(models.Model):
	user = models.ForeignKey(User)
	tel_number = models.CharField(max_length=13)
	location = models.CharField(max_length=255, blank=True, null=True)


"""
the cart model repersent the cart table
on our db and has a foreign key of the customer
to the Customer table
"""


class Cart(models.Model):
	customer = models.OneToOneField(Customer)
	active = models.BooleanField(default=True)
	order_time = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name = "Customer Order"
		verbose_name_plural = "Customer Orders"

	# a helper method to add a food to the cart
	def add_to_cart(self, food_id):
		food = Food.objects.get(pk=food_id)
		try:
			preexisting_order = FoodOrder.objects.get(food=food, cart=self)
			preexisting_order.quantity += 1
			preexisting_order.save()
		except FoodOrder.DoesNotExist:
			new_order = FoodOrder.objects.create(
				food=food,
				cart=self,
				quantity=1
			)

			new_order.save()

	# helper method to remove a food from the cart
	def remove_from_cart(self, food_id):
		food_to_remove = Food.objects.get(pk=food_id)
		try:
			preexisting_order = FoodOrder.objects.get(food=food_to_remove, cart=self)

			if preexisting_order.quantity > 1:
				preexisting_order.quantity -= 1
				preexisting_order.save()
			else:
				preexisting_order.delete()

		except FoodOrder.DoesNotExist:
			pass


"""
the food order class that represent the
food order table, it has a foreign key
relationship to the Food, Cart
"""


class FoodOrder(models.Model):
	food = models.ForeignKey(Food)
	cart = models.ForeignKey(Cart)
	quantity = models.IntegerField()
	order_time = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return "Food Order"

	class Meta:
		verbose_name = "Ordered Food"
		verbose_name_plural = "Ordered Foods List"
		ordering = ["-order_time"]

	def food_(self):
		return self.food.food_name

	def customer_(self):
		return self.cart.customer.tel_number


class Payment(models.Model):
	cart = models.ForeignKey(Cart)
	total = models.FloatField()
	payed = models.BooleanField(default=False)
	card_name = models.CharField(max_length=255)
	card_number = models.CharField(max_length=19, default='XXXX-XXXX-XXXX-XXXX')
	received = models.BooleanField(default=False)

	class Meta:
		verbose_name = "Customer Payment"
		verbose_name_plural = "Customer Payments"

	def customer_name(self):
		return self.cart.customer.tel_number

	def order(self):
		orders = FoodOrder.objects.filter(cart=self.cart)
		order_list = []
		for order in orders:
			order_list.append(order.food.food_name)
		return order_list

	order.allow_tags = True

	def quantity(self):
		orders = FoodOrder.objects.filter(cart=self.cart)
		order_list = []
		for order in orders:
			order_list.append(order.quantity)
		return order_list

	quantity.allow_tags = True

order/forms.py
__author__ = 'peter'

from django import forms

"""
	our customer form that
	is been showed at the index page
"""


class CustomerForm(forms.Form):
	tel_number = forms.CharField()

	class Meta:
		widgets = {
			'tel_number': forms.NumberInput(attrs=
			                                {'class': 'validate',
			                                 'number': 'text',
			                                 'id': 'tel_number',
			                                 'placeholder': 'Enter Phone Number'
			                                 })
		}


class PaymentForm(forms.Form):
	card_name = forms.CharField()
	card_number = forms.CharField()

	class Meta:
		widget = {
			'card_name': forms.TextInput(attrs={'class': 'validate', 'type': 'text', 'id': 'card_name'}),
			'card_number': forms.TextInput(attrs={'class': 'validate', 'type': 'number', 'id': 'card_number'})
		}

order/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from models import *
from forms import *
from  django.views import generic
from django.conf.urls import url

"""
this view is reponsible for getting all the
available food and present it to the html template
food_list.html.
"""


class FoodMenuView(generic.ListView):
	# the queryset for getting all food with the availability status of true
	queryset = Food.objects.filter(food_availability=True)
	# tell the html template to only show 12 food maximum per-page and pyt the rest in the next and previous
	paginate_by = 12
	# our html template that would show all the available food
	template_name = 'order/_food_menu.html'


"""
this view is the first page to be showned when
the user or customer visit out fast food application
"""


def index_page(request):
	# create an empty dictionary that would hold some variable to be used in the html
	context_dict = {}
	# since our index page has a form that accept customer tel_number
	# let check if the customer make a post request to initiate an order
	# if it is a post then we process what is inside the form basically just the tel_number
	if request.method == 'POST':
		# let get the form values from the customer form
		customer_form = CustomerForm(data=request.POST)
		# is the form valid(tgat means if the customer has actually fill the form and the form contain some info
		if customer_form.is_valid() and customer_form.is_bound:
			# get the form data from the customer form
			form_data = customer_form.data
			# we just need only the customer tel_number as his order number and store it inside the
			# customer_tel_number variable
			customer_tel_number = form_data['tel_number']
			# first let check if the customer telephone number is already registered in our db
			# so as not allow two different number but need better way to go around it ie (FUTURE ENHANCEMENT)
			is_customer_already_registered = None  # assuming the customer is not registered

			try:
				# let check by getting the customer by passing the tel_number from the form as a criteria
				# and store it inside the is_custoer_already_registered variable
				is_customer_already_registered = Customer.objects.get(tel_number=customer_tel_number)
			except Customer.DoesNotExist:
				# incase the customer with this particular tel_number does not exits we should
				# prevent some error and continue to the else block after the
				pass
			# if the customer is already registered ok we just need to logged them into the system
			# and not register them again
			if is_customer_already_registered:
				# we authenticated the customer by using the tel_number as their username
				# and default as their password for all customer
				user = authenticate(username=customer_tel_number, password='default')
				# if everything is succesfull logged them in
				if user:
					login(request, user)

					a_cart = None
					# check if the customer has a cart
					try:
						a_cart = Cart.objects.get(customer=is_customer_already_registered)
					except Cart.DoesNotExist:
						pass

					# let check if the customer cart is not active
					if a_cart and not a_cart.active:
						try:
							#if it is not let delete all the item in the cart
							orders = FoodOrder.objects.filter(cart=a_cart)
							orders.delete()
						except FoodOrder.DoesNotExist:
							pass
						# then make the cart active
						a_cart.active = True
						a_cart.save()
			else:
				# eles the customer is not in our system let automatically registered them as
				# a new user and a customer in our system
				a_user = User.objects.create_user(username=customer_tel_number, password="default")
				a_customer = Customer.objects.create(
					user=a_user,
					tel_number=customer_tel_number
				)
				# if all the database operation for saving the customer is sucessfull then we
				# automatically logged the customer into the system
				if a_customer:
					user = authenticate(username=customer_tel_number, password='default')
					login(request, user)
		# if everything was ok then we redirect the user to the menu list to see all food
		return HttpResponseRedirect('/fast/menu')
	else:
		# ok it is a get method so we show the customer form on the index page
		customer_form = CustomerForm()
	# add the customer form object to the dictionary to be passed to the template for processing
	context_dict['customer_form'] = customer_form
	# return every thing including the dictionary
	return render(request, template_name='order/_index.html', context=context_dict)


"""
this view is responsible for adding a food
from the menu to the order/cart and also increasing
the particular food quantity
Remember this view recieve a AJAX call
"""


def add_item_to_cart(request):
	# we are sending an AJAX (javascript get call to this view) with the food_id
	# to be added passed to it. Get the food_id from the request
	food_id = request.GET['food_id']
	# assuming the current_custoer cart is empty
	current_cart = None
	try:
		# check does the food the customer want to add to his/her
		# order exits
		food_to_add = Food.objects.get(pk=food_id)
	except Food.DoesNotExist:
		# remeber we are keeping this in check of any error
		pass
	else:
		# ok no error found that food actually exits
		try:
			# let track the customer who is making this request by getting the
			# customer information by passing the request.user as a query for
			# getting the current_customer
			current_customer = Customer.objects.get(user=request.user)
			# get the customer cart if  he has any and it is active
			cart = Cart.objects.get(customer=current_customer, active=True)
		except Cart.DoesNotExist, Customer.DoesNotExist:
			# check whether it does not exits which if the cart does not
			# create it and assing the customer as a foriegn key to the cart
			current_customer = Customer.objects.get(user=request.user)
			# cretae the cart for the current customer
			cart = Cart.objects.create(
				customer=current_customer
			)
			# save the cart
			cart.save()
			pass
		# add the food to the cart
		cart.add_to_cart(food_id)

		current_cart = cart

	# get all order item that are in the current cart  by getting it through the filter
	ordered_item = FoodOrder.objects.filter(cart=current_cart)
	# return the count of the ordered items
	print "Increasing Items now is ", ordered_item.count()
	return HttpResponse(ordered_item.count())


# remove a food from the carts by decreasing a particular order
def remove_food_from_cart(request):
	current_cart = None
	# the food id from the javascript request
	food_id = request.GET['food_id']
	try:
		food_to_remove = Food.objects.get(pk=food_id)
	except Food.DoesNotExist:
		pass
	else:
		current_customer = Customer.objects.get(user=request.user)
		cart = Cart.objects.get(customer=current_customer, active=True)
		current_cart = cart
		cart.remove_from_cart(food_id)

	ordered_item = FoodOrder.objects.filter(cart=current_cart)
	print "Removing Items now is ", ordered_item.count()
	return HttpResponse(ordered_item.count())


# when the customer is ready to pay
@login_required(login_url='/fast/')
def get_food_from_cart(request):
	context_dict = {}

	current_customer = Customer.objects.get(user=request.user)

	try:
		cart = Cart.objects.get(customer=current_customer)
	except Cart.DoesNotExist:
		return HttpResponseRedirect('/fast/menu/')
	if not cart.active:
		return HttpResponseRedirect('/fast/menu/')
	orders = FoodOrder.objects.filter(cart=cart)
	total = 0
	count = 0
	food_items = []

	for order in orders:
		food_items.append(order.food)
		total += (order.food.food_price * order.quantity)
		count += order.quantity
	if request.method == 'POST':
		payment_form = PaymentForm(request.POST)
		if payment_form.is_valid() and payment_form.is_bound:
			# payment details where correct
			payment_information = payment_form.data
			card_name = payment_information['card_name']
			card_number = payment_information['card_number']
			new_customer_payment = Payment.objects.create(
				cart=cart,
				card_name=card_name,
				card_number=card_number,
				total=total,
				payed=True
			)
			cart.active = False
			cart.save()
			logout(request)
		return HttpResponseRedirect(redirect_to='/fast/payment-successful/')
	else:
		# payment details was not correct
		payment_form = PaymentForm()

	context_dict['payment_form'] = payment_form
	context_dict['total'] = total
	context_dict['count'] = count
	context_dict['food_list'] = food_items
	context_dict['orders'] = orders

	return render(request, template_name='order/_view_cart.html', context=context_dict)


def success_full_payment(request):
	return render(request, template_name='order/_successfull_payment.html', context={})


# the function that logs the customer out of the system
# the user must be logged in before
@login_required(login_url='/fast/')
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/fast/')


def handler404(request):
	response = render_to_response('order/404.html', {}, context_instance=RequestContext(request))
	response.status_code = 404
	return response


def handler500(request):
	response = render_to_response('order/500.html', {}, context_instance=RequestContext(request))
	response.status_code = 500
	return response

templates/order/_customer_form.html
{% include 'order/base.html' %}



{% block content %}
    <form method="post" action="/fast/reg/" xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div class="row">
        <div class="col s10">
        {{ customer_form.tel_number }}
        </div>
    </div>
    <button class="btn-large waves-effect waves-light teal lighten-1" type="submit">
        Place Order
    </button>
</form>
{% endblock %}

templates/order/_food_menu.html
{% extends 'order/base.html' %}

{% block title %}
    Menu
{% endblock %}

{% block content %}
    <div class="container">
        <div class="section">
            <div class="row">
                {% for food in object_list %}
                    <div class="col s3 md2">
                        <div class="card">
                            <div class="card-image">
                                <img style="width: 220px; height: 200px" src="{{ food.food_image.url }}"/>
                                <span class="card-title">{{ food.food_name }}</span>
                            </div>
                            <div class="card-content">
                                &#8358;{{ food.food_price }}
                            </div>
                            {% if user.is_authenticated %}
                                <div class="card-action">
                                    <button class="btn-floating" id="food-id" data-food="{{ food.id }}"><i
                                            class="mdi-content-add"></i></button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/order/_footer.html
<footer class="page-footer red darken-1">
    <div class="container">

    </div>
    <div class="footer-copyright">
        <div class="container">
            Design by <a class="brown-text text-lighten-3" href="http:pitaside.blogspot.com">Maryam</a>
        </div>
    </div>
</footer>

templates/order/_header.html
{% load staticfiles %}
<div class="navbar-fixed">
    <nav class="red lighten-1" role="navigation">

        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'index' %}" class="brand-logo">
                <img src="{% static 'order/images/photo1.jpg' %}" width="100" height="65"/>
            </a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'menu' %}">Menu</a></li>
                <li><a href="{% url 'cart' %}">
                    My Orders
                    <span id="cart_item">{{ count }}</span></a></li>
                <li><a href="/admin">Admin</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    <li>Number :: {{ user.username }}</li>
                {% endif %}
            </ul>
            <a data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>
</div>

templates/order/_index.html
{% extends 'order/base.html' %}
{% load staticfiles %}

{% block title %}
    Welcome
{% endblock %}



{% block content %}

    <div id="index-banner" class="parallax-container">
        <div class="section no-pad-bot">
            <div class="container">

                <div class="row center">
                    <div class="row">
                        <div class="col s10 m7 offset-l2">
                            <div class="card">
                                <div class="card-image">
                                    <img src="{% static 'order/images/photo2.jpg' %}">
                                    <span class="card-title">Burger and Pizza has never been served right before....</span>
                                </div>
                                <div class="card-content">
                                    <form method="post" action="/fast/" xmlns="http://www.w3.org/1999/html">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col s8 ">
                                                {{ customer_form.tel_number }}
                                            </div>
                                            <div class="col-s3">
                                                <button class="btn-large waves-effect waves-light teal lighten-1"
                                                        type="submit">
                                                    Place Order
                                                </button>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <br><br>

            </div>
        </div>
        <div class="parallax">
            <div class="parallax"><img src="{% static 'order/images/photo4.jpg' %}"></div>
        </div>
    </div>


{% endblock %}

templates/order/_reservation_form.html
<form id="order_form" method="post" action="#">
    {% csrf_token %}
    <div class="row">
       <div class="input-field col s6">
            <i class="material-icons prefix">verified_user</i>
           {{ order_form.order_number }}

       </div>
    </div>
</form>

templates/order/_successfull_payment.html
{% extends 'order/base.html' %}
{% load static %}
{% load staticfiles %}

{% block title %}
    Payment Successfull
{% endblock %}



{% block content %}
    <div class="container">
        <div class="section">
            <div class="valign-wrapper">

                <div class="row">
                    <div class="col s10 m7 offset-l2">
                        <div class="card">
                            <div class="card-image">
                                <img src="{% static  'order/images/giphy.gif' %}">
                                <span class="card-title">Payment Successful</span>
                            </div>
                            <div class="card-content">
                                <p>Thanks for patronizing our fast-food resturant, always come back for more meals.
                                    Thanks for patronizing our fast-food resturant, always come back for more meals.
                                </p>
                            </div>
                            <div class="card-action">
                                <a href="{% url 'menu' %}">Back</a>
                                <a href="{% url 'menu' %}">About</a>
                            </div>
                        </div>
                    </div>
                </div>


            </div>

        </div>

    </div>
{% endblock %}

templates/order/_view_cart.html
{% extends 'order/base.html' %}

{% block title %}
    Order
{% endblock %}


{% block content %}
    <div class="container">
        {% if  user.is_authenticated %}
            <div class="row">
                <div class="col s7">

                    <div class="collection with-header">
                        <div class="collection-header">
                            <h4 class="center-align">
                                Orders
                            </h4>
                        </div>
                        {% if  orders %}
                            {% for order in orders %}
                                <li class="collection-item avatar">
                                    <img src="{{ order.food.food_image.url }}" alt="" class="circle">
                                    <span class="title">{{ order.food.food_name }}</span>

                                    <p>
                                        <strong>&#8358;{{ order.food.food_price }}</strong>
                                        <strong>Qty <b>({{ order.quantity }})</b> </strong>
                                    </p>

                                    <div class="secondary-content">
                                <span class="add-item">
                                    <button class="btn-floating" id="food-add" data-food="{{ order.food_id }}">
                                        <i class="mdi-content-add"></i>
                                    </button>
                                </span>
                                <span class="remove-item">
                                    <button class="btn-floating" id="food-remove" data-food="{{ order.food_id }}">
                                        <i class="mdi-content-remove"></i>
                                    </button>
                                </span>

                                    </div>
                                </li>
                            {% endfor %}
                        {% else %}
                            <div class="row">
                                You current orders is empty
                            </div>
                        {% endif %}

                    </div>
                </div>

                <div class="col s5">

                    <div class="collection with-header">
                        <div class="collection-header">
                            <h5 class="center-align">
                                Payment
                            </h5>
                        </div>

                        <div class="collection-item">
                            <p class="right-align">
                                <strong><b> TOTAL COST</b></strong> <br>&#8358;{{ total }}
                            </p>

                        </div>
                        <div class="collection-item">
                            <div class="row">
                                <form action="{% url 'cart' %}" method="POST" class="col s12">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col 12">
                                            <span class="center-align">Please Card Details</span>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <i class="mdi-action-account-circle prefix"></i>
                                            {{ payment_form.card_name }}
                                            <label for="id_card_name">Card Name</label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="input-field col s12">
                                            <i class="mdi-action-credit-card prefix"></i>
                                            {{ payment_form.card_number }}
                                            <label for="card_number">Card Number</label>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-10">
                                            <button class="btn waves-effect waves-light" type="submit" name="action">
                                                Proceed
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="col s7">
                    Please Login
                </div>
            </div>
        {% endif %}


    </div>
{% endblock %}

templates/order/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'order/css/materialize.min.css' %}" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'order/css/style.css' %}" media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="body">

{% include 'order/_header.html' %}
<div class="main">
    {% block content %}
    {% endblock %}
</div>
{% include 'order/_footer.html' %}


<script src="{% static 'order/js/jquery.js' %}"></script>
<script src="{% static 'order/js/materialize.min.js' %}"></script>
<script src="{% static 'order/js/init.js' %}"></script>
</body>
</html>